#!/usr/bin/env sh


#rexreplace 
#rr -[0-9][0-9][0-9][0-9][0-9][0-9][0-9]* "-$(date-now --format=YYYYMMDDHHmmss)" $1 -G ;
#rr '(Version: [0-9\.]*)-?.*' '$1'"-$(git rev-parse HEAD | cut -c1-10 )" $1 -G ;
rr '(Version:[\s]*[0-9\.]*)-?.*' '$1'"-$(($(git rev-list --all --count) - $2))" $1 -G ;

touch $1;